hyperparameters:
  depth_threshold: 0.8
  dbscan_eps: 0.5
  dbscan_min_points: 100
  filter_cluster_size: 50
  voxel_size: 0.9

voting:
  background_weights: 0.02  # Assuming 1/50 should be represented as 0.02
  image_filte_rate: 3

visualization:
  visualize_images: false  # Corrected 'flase' to 'false'
  visualize_dbscan: false


pathes:
  path_to_project: '/home/negar/secondssd/opendronemap/datasets/project_neighboor'
  path_to_ply_file: '/home/negar/secondssd/opendronemap/datasets/project_neighboor/odm_filterpoints/point_cloud.ply'
  path_to_cameras: '/home/negar/secondssd/opendronemap/datasets/project_neighboor/opensfm/reconstruction.json'
  path_to_segmentation: '/home/negar/secondssd/opendronemap/ply_semantic_segmentation/2D_segmentation/results/sam_l_neighboor_more_classes_white'
